language: rust
rust:
  - stable

git:
  depth: 1
  quiet: true

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - "$HOME/.cargo"
before_cache:
  - rm -rf "$HOME/.cargo/registry"

script:
  - cargo build
  - if [ -n "$GITHUB_TOKEN" ]; then FEATURES=('--github-token' "$GITHUB_TOKEN"); else FEATURES=(); fi
  - RUST_COMMIT=$(git ls-remote https://github.com/rust-lang/rust master | awk '{print $1}')
  - cargo run -- "${FEATURES[@]}"
  - rustc +"$RUST_COMMIT" -vV
  - rustc +"$RUST_COMMIT" -vV | grep "$RUST_COMMIT"
