language: rust
rust:
  - stable

git:
  depth: 1

cache:
  directories:
    - "$HOME/.cargo"
before_cache:
  - rm -rf "$HOME/.cargo/registry"

script:
  - cargo install --debug --force --path .
  - >
      if [ -n "$GITHUB_TOKEN" ]; then
        RUST_COMMIT=$(rustup-toolchain-install-master --github-token "$GITHUB_TOKEN") &&
        echo $RUST_COMMIT &&
        rustc +"$RUST_COMMIT" -vV &&
        rustc +"$RUST_COMMIT" -vV | grep "$RUST_COMMIT";
      fi
