[package]
name = "rustup-toolchain-install-master"
version = "1.6.0"
authors = ["kennytm <kennytm@gmail.com>"]
description = "Install master rustc toolchain into rustup"
repository = "https://github.com/kennytm/rustup-toolchain-install-master"
readme = "README.md"
keywords = ["rustup"]
categories = ["development-tools"]
license = "MIT"

[badges]
maintenance = { status = "passively-maintained" }
travis-ci = { repository = "kennytm/rustup-toolchain-install-master" }
is-it-maintained-issue-resolution = { repository = "kennytm/rustup-toolchain-install-master" }
is-it-maintained-open-issues = { repository = "kennytm/rustup-toolchain-install-master" }

[dependencies]
failure = "0.1"
home = "0.3"
pbr = "1"
reqwest = "0.9"
structopt = "0.2"
tar = "0.4"
tee = "0.1"
tempfile = "3"
xz2 = "0.1"
ansi_term = "0.11"
